/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated.app.index'
import { Route as AuthenticatedAppProfileRouteImport } from './routes/_authenticated.app.profile'
import { Route as AuthenticatedAppFriendsRouteImport } from './routes/_authenticated.app.friends'
import { Route as AuthenticatedAppChatConvIdRouteImport } from './routes/_authenticated.app.chat.$convId'
import { Route as AuthenticatedAppCallConvIdRouteImport } from './routes/_authenticated.app.call.$convId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppProfileRoute = AuthenticatedAppProfileRouteImport.update({
  id: '/app/profile',
  path: '/app/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppFriendsRoute = AuthenticatedAppFriendsRouteImport.update({
  id: '/app/friends',
  path: '/app/friends',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppChatConvIdRoute =
  AuthenticatedAppChatConvIdRouteImport.update({
    id: '/app/chat/$convId',
    path: '/app/chat/$convId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppCallConvIdRoute =
  AuthenticatedAppCallConvIdRouteImport.update({
    id: '/app/call/$convId',
    path: '/app/call/$convId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/friends': typeof AuthenticatedAppFriendsRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/call/$convId': typeof AuthenticatedAppCallConvIdRoute
  '/app/chat/$convId': typeof AuthenticatedAppChatConvIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/friends': typeof AuthenticatedAppFriendsRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/call/$convId': typeof AuthenticatedAppCallConvIdRoute
  '/app/chat/$convId': typeof AuthenticatedAppChatConvIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app/friends': typeof AuthenticatedAppFriendsRoute
  '/_authenticated/app/profile': typeof AuthenticatedAppProfileRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/call/$convId': typeof AuthenticatedAppCallConvIdRoute
  '/_authenticated/app/chat/$convId': typeof AuthenticatedAppChatConvIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app/friends'
    | '/app/profile'
    | '/app/'
    | '/app/call/$convId'
    | '/app/chat/$convId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/friends'
    | '/app/profile'
    | '/app'
    | '/app/call/$convId'
    | '/app/chat/$convId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app/friends'
    | '/_authenticated/app/profile'
    | '/_authenticated/app/'
    | '/_authenticated/app/call/$convId'
    | '/_authenticated/app/chat/$convId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/profile': {
      id: '/_authenticated/app/profile'
      path: '/app/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AuthenticatedAppProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/friends': {
      id: '/_authenticated/app/friends'
      path: '/app/friends'
      fullPath: '/app/friends'
      preLoaderRoute: typeof AuthenticatedAppFriendsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/chat/$convId': {
      id: '/_authenticated/app/chat/$convId'
      path: '/app/chat/$convId'
      fullPath: '/app/chat/$convId'
      preLoaderRoute: typeof AuthenticatedAppChatConvIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/call/$convId': {
      id: '/_authenticated/app/call/$convId'
      path: '/app/call/$convId'
      fullPath: '/app/call/$convId'
      preLoaderRoute: typeof AuthenticatedAppCallConvIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAppFriendsRoute: typeof AuthenticatedAppFriendsRoute
  AuthenticatedAppProfileRoute: typeof AuthenticatedAppProfileRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppCallConvIdRoute: typeof AuthenticatedAppCallConvIdRoute
  AuthenticatedAppChatConvIdRoute: typeof AuthenticatedAppChatConvIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppFriendsRoute: AuthenticatedAppFriendsRoute,
  AuthenticatedAppProfileRoute: AuthenticatedAppProfileRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppCallConvIdRoute: AuthenticatedAppCallConvIdRoute,
  AuthenticatedAppChatConvIdRoute: AuthenticatedAppChatConvIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
