/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated.app.index'
import { Route as AuthenticatedAppStoriesRouteImport } from './routes/_authenticated.app.stories'
import { Route as AuthenticatedAppProfileRouteImport } from './routes/_authenticated.app.profile'
import { Route as AuthenticatedAppPostStoryRouteImport } from './routes/_authenticated.app.post-story'
import { Route as AuthenticatedAppFriendsRouteImport } from './routes/_authenticated.app.friends'
import { Route as AuthenticatedAppCallsRouteImport } from './routes/_authenticated.app.calls'
import { Route as AuthenticatedAppUserUserIdRouteImport } from './routes/_authenticated.app.user.$userId'
import { Route as AuthenticatedAppChatConvIdRouteImport } from './routes/_authenticated.app.chat.$convId'
import { Route as AuthenticatedAppCallConvIdRouteImport } from './routes/_authenticated.app.call.$convId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppStoriesRoute = AuthenticatedAppStoriesRouteImport.update({
  id: '/app/stories',
  path: '/app/stories',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppProfileRoute = AuthenticatedAppProfileRouteImport.update({
  id: '/app/profile',
  path: '/app/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppPostStoryRoute =
  AuthenticatedAppPostStoryRouteImport.update({
    id: '/app/post-story',
    path: '/app/post-story',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppFriendsRoute = AuthenticatedAppFriendsRouteImport.update({
  id: '/app/friends',
  path: '/app/friends',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppCallsRoute = AuthenticatedAppCallsRouteImport.update({
  id: '/app/calls',
  path: '/app/calls',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppUserUserIdRoute =
  AuthenticatedAppUserUserIdRouteImport.update({
    id: '/app/user/$userId',
    path: '/app/user/$userId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppChatConvIdRoute =
  AuthenticatedAppChatConvIdRouteImport.update({
    id: '/app/chat/$convId',
    path: '/app/chat/$convId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppCallConvIdRoute =
  AuthenticatedAppCallConvIdRouteImport.update({
    id: '/app/call/$convId',
    path: '/app/call/$convId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/calls': typeof AuthenticatedAppCallsRoute
  '/app/friends': typeof AuthenticatedAppFriendsRoute
  '/app/post-story': typeof AuthenticatedAppPostStoryRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/stories': typeof AuthenticatedAppStoriesRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/call/$convId': typeof AuthenticatedAppCallConvIdRoute
  '/app/chat/$convId': typeof AuthenticatedAppChatConvIdRoute
  '/app/user/$userId': typeof AuthenticatedAppUserUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/calls': typeof AuthenticatedAppCallsRoute
  '/app/friends': typeof AuthenticatedAppFriendsRoute
  '/app/post-story': typeof AuthenticatedAppPostStoryRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/stories': typeof AuthenticatedAppStoriesRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/call/$convId': typeof AuthenticatedAppCallConvIdRoute
  '/app/chat/$convId': typeof AuthenticatedAppChatConvIdRoute
  '/app/user/$userId': typeof AuthenticatedAppUserUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app/calls': typeof AuthenticatedAppCallsRoute
  '/_authenticated/app/friends': typeof AuthenticatedAppFriendsRoute
  '/_authenticated/app/post-story': typeof AuthenticatedAppPostStoryRoute
  '/_authenticated/app/profile': typeof AuthenticatedAppProfileRoute
  '/_authenticated/app/stories': typeof AuthenticatedAppStoriesRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/call/$convId': typeof AuthenticatedAppCallConvIdRoute
  '/_authenticated/app/chat/$convId': typeof AuthenticatedAppChatConvIdRoute
  '/_authenticated/app/user/$userId': typeof AuthenticatedAppUserUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app/calls'
    | '/app/friends'
    | '/app/post-story'
    | '/app/profile'
    | '/app/stories'
    | '/app/'
    | '/app/call/$convId'
    | '/app/chat/$convId'
    | '/app/user/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/calls'
    | '/app/friends'
    | '/app/post-story'
    | '/app/profile'
    | '/app/stories'
    | '/app'
    | '/app/call/$convId'
    | '/app/chat/$convId'
    | '/app/user/$userId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app/calls'
    | '/_authenticated/app/friends'
    | '/_authenticated/app/post-story'
    | '/_authenticated/app/profile'
    | '/_authenticated/app/stories'
    | '/_authenticated/app/'
    | '/_authenticated/app/call/$convId'
    | '/_authenticated/app/chat/$convId'
    | '/_authenticated/app/user/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/stories': {
      id: '/_authenticated/app/stories'
      path: '/app/stories'
      fullPath: '/app/stories'
      preLoaderRoute: typeof AuthenticatedAppStoriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/profile': {
      id: '/_authenticated/app/profile'
      path: '/app/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AuthenticatedAppProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/post-story': {
      id: '/_authenticated/app/post-story'
      path: '/app/post-story'
      fullPath: '/app/post-story'
      preLoaderRoute: typeof AuthenticatedAppPostStoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/friends': {
      id: '/_authenticated/app/friends'
      path: '/app/friends'
      fullPath: '/app/friends'
      preLoaderRoute: typeof AuthenticatedAppFriendsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/calls': {
      id: '/_authenticated/app/calls'
      path: '/app/calls'
      fullPath: '/app/calls'
      preLoaderRoute: typeof AuthenticatedAppCallsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/user/$userId': {
      id: '/_authenticated/app/user/$userId'
      path: '/app/user/$userId'
      fullPath: '/app/user/$userId'
      preLoaderRoute: typeof AuthenticatedAppUserUserIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/chat/$convId': {
      id: '/_authenticated/app/chat/$convId'
      path: '/app/chat/$convId'
      fullPath: '/app/chat/$convId'
      preLoaderRoute: typeof AuthenticatedAppChatConvIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/call/$convId': {
      id: '/_authenticated/app/call/$convId'
      path: '/app/call/$convId'
      fullPath: '/app/call/$convId'
      preLoaderRoute: typeof AuthenticatedAppCallConvIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAppCallsRoute: typeof AuthenticatedAppCallsRoute
  AuthenticatedAppFriendsRoute: typeof AuthenticatedAppFriendsRoute
  AuthenticatedAppPostStoryRoute: typeof AuthenticatedAppPostStoryRoute
  AuthenticatedAppProfileRoute: typeof AuthenticatedAppProfileRoute
  AuthenticatedAppStoriesRoute: typeof AuthenticatedAppStoriesRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppCallConvIdRoute: typeof AuthenticatedAppCallConvIdRoute
  AuthenticatedAppChatConvIdRoute: typeof AuthenticatedAppChatConvIdRoute
  AuthenticatedAppUserUserIdRoute: typeof AuthenticatedAppUserUserIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppCallsRoute: AuthenticatedAppCallsRoute,
  AuthenticatedAppFriendsRoute: AuthenticatedAppFriendsRoute,
  AuthenticatedAppPostStoryRoute: AuthenticatedAppPostStoryRoute,
  AuthenticatedAppProfileRoute: AuthenticatedAppProfileRoute,
  AuthenticatedAppStoriesRoute: AuthenticatedAppStoriesRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppCallConvIdRoute: AuthenticatedAppCallConvIdRoute,
  AuthenticatedAppChatConvIdRoute: AuthenticatedAppChatConvIdRoute,
  AuthenticatedAppUserUserIdRoute: AuthenticatedAppUserUserIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
